//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMMaps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public Board()
        {
            this.BoardImages = new HashSet<BoardImage>();
            this.Demos = new HashSet<Demo>();
            this.Map_Boards = new HashSet<Map_Boards>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BoardTypeID { get; set; }
        public Nullable<int> DMAID { get; set; }
        public Nullable<int> ProductionVendorID { get; set; }
        public string BoardNumber { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Facing { get; set; }
        public string SideOfStreet { get; set; }
        public string ReadDirection { get; set; }
        public bool Illuminated { get; set; }
        public string BoardHeight { get; set; }
        public string BoardWidth { get; set; }
        public Nullable<int> Weekly18PlusImpressions { get; set; }
        public Nullable<int> TabPanelID { get; set; }
        public string LinkToProductionSpecs { get; set; }
        public Nullable<int> BoardRatingID { get; set; }
        public string Notes { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> BoardVendorID { get; set; }
    
        public virtual BoardType BoardType { get; set; }
        public virtual DMA DMA { get; set; }
        public virtual BoardVendor BoardVendor { get; set; }
        public virtual ProductionVendor ProductionVendor { get; set; }
        public virtual ICollection<BoardImage> BoardImages { get; set; }
        public virtual ICollection<Demo> Demos { get; set; }
        public virtual BoardRating BoardRating { get; set; }
        public virtual ICollection<Map_Boards> Map_Boards { get; set; }
    }
}
