//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMMaps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureType
    {
        public FeatureType()
        {
            this.MapStyle = new HashSet<MapStyle>();
            this.MapStyleDefaults = new HashSet<MapStyleDefault>();
        }
    
        public int ID { get; set; }
        public string FeatureType1 { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<MapStyle> MapStyle { get; set; }
        public virtual ICollection<MapStyleDefault> MapStyleDefaults { get; set; }
    }
}
