//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMMaps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinType
    {
        public PinType()
        {
            this.Pin = new HashSet<Pin>();
            this.Map_Boards = new HashSet<Map_Boards>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Pin> Pin { get; set; }
        public virtual ICollection<Map_Boards> Map_Boards { get; set; }
    }
}
