//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMMaps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RCMMapsEntities : DbContext
    {
        public RCMMapsEntities()
            : base("name=RCMMapsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeatureType> FeatureTypes { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<MapStyle> MapStyles { get; set; }
        public virtual DbSet<Pin> Pins { get; set; }
        public virtual DbSet<PinType> PinTypes { get; set; }
        public virtual DbSet<BoardImage> BoardImages { get; set; }
        public virtual DbSet<BoardRating> BoardRatings { get; set; }
        public virtual DbSet<Board> Boards { get; set; }
        public virtual DbSet<BoardType> BoardTypes { get; set; }
        public virtual DbSet<Demo> Demos { get; set; }
        public virtual DbSet<DMA> DMAs { get; set; }
        public virtual DbSet<ProductionVendor> ProductionVendors { get; set; }
        public virtual DbSet<BoardVendor> BoardVendors { get; set; }
        public virtual DbSet<Map_Boards> Map_Boards { get; set; }
        public virtual DbSet<UserSearch> UserSearches { get; set; }
        public virtual DbSet<MapStyleDefault> MapStyleDefaults { get; set; }
        public virtual DbSet<MapDefault> MapDefaults { get; set; }
    }
}
