//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMMaps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSearch
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string MapsSearchString { get; set; }
        public string BoardsSearchString { get; set; }
        public string BoardType { get; set; }
        public string DMA { get; set; }
        public string Vendor { get; set; }
    }
}
